### ISSUE TITLE
关于风格迁移效果问题

### ISSUE THREAD

**Issue by ArcPi** [TONYCHANBB/Chinese_painting-style#1]
你好，用你改进的算法和原始算法跑马的风格迁移，效果几乎一样。您测试过其他马的风格吗？我测试了一下，在原始算法效果不好的，在你的算法上也不好。没入门小白，望解答一下
![testhorse](https://user-images.githubusercontent.com/26409780/47263331-20ca2580-d532-11e8-868a-d1cf2993f724.jpg)
这是原始
![800horse_output](https://user-images.githubusercontent.com/26409780/47263361-ae0d7a00-d532-11e8-8a89-b41f59068579.jpg)

这是改进的

**Comment by TONYCHANBB** [comment]
参数可以多调调试试
